[package]
name = "gash"
description = "Brute force your git hash!"
version = "0.1.0"
authors = ["acheronfail <acheronfail@gmail.com>"]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap" }
rayon = "1.3.0"
regex = "1.3.6"
rust-crypto = "0.2.36"
