[package]
name = "gash"
description = "Brute force your git hash!"
version = "0.5.0"
authors = ["Callum Oz <acheronfail@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Unlicense OR MIT"
homepage = "https://github.com/acheronfail/gash"
repository = "https://github.com/acheronfail/gash"
build = "ci/build-clap-v3.rs"

[dependencies]
clap = { version = "3.0.0-beta.1", git = "https://github.com/clap-rs/clap" }
hex = "0.4.2"
rayon = "1.3.0"
regex = "1.3.6"
sha-1 = "0.8.2"
termcolor = "1.1.0"

[build-dependencies]
clap = { version = "3.0.0-beta.1", git = "https://github.com/clap-rs/clap" }
clap_generate = { version = "3.0.0-beta.1", git = "https://github.com/clap-rs/clap" }
